workflows:
  version: 2
  build:
    jobs:
      - tests
      - deploy:
          filters:
            branches:
                  only:
                    - heroku
          requires:
            - tests

defaults: &defaults
  working_directory: ~/urug-bot
  docker:
    - image: &circle_image circleci/ruby:2.3.3

version: 2
jobs:
  tests:
    <<: *defaults
    docker:
      - image: *circle_image
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"
          APP_ENV: test
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: urug-bot-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: urug-bot-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run rspec
      - type: shell
        command: bundle exec rspec spec

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results

  deploy:
      <<: *defaults
      steps:
        - run:
            name: Run setup script
            command: bash .circleci/setup-heroku.sh
        - add_ssh_keys:
            fingerprints:
              - "5f:3d:78:5d:45:9c:57:d8:1f:35:3e:b4:0d:05:5a:3e"
        - run:
            name: Deploy Master to Heroku
            command: |
              git push heroku master
